### ISSUE TITLE
批量转换

### ISSUE THREAD

**Issue by aliofwind** [HITIKM/DanmakuFactory#1]
因为是录制直播，所以每天都有几十个xml弹幕文件需要转ass，希望能提供批量转换功能，或者提供命令行调用

**Comment by HITIKM** [comment]
非常感谢您的建议！其实批量转换是我在设计的开始就想要加入的，不过第一个版本太过仓促只实现了一些比较基本的东西。因为最近在考试，所以新版本可能要等到七月中旬，新版本还会针对将弹幕字幕压制到视频做一些功能上的改进，还请您继续关注！

**Comment by HITIKM** [comment]
可以的话提供一下邮箱，更新之后第一时间告诉你

**Comment by aliofwind** [comment]
谢谢，邮箱是aliofwind@gmail.com

**Comment by HITIKM** [comment]
请查收

**Comment by aliofwind** [comment]
已收到，谢谢
