### ISSUE TITLE
颜色信息（彩色弹幕）转化后均为白色

### ISSUE THREAD

**Issue by starxjys** [HITIKM/DanmakuFactory#2]
如题

**Comment by HITIKM** [comment]
您好，此bug在之前从未出现过，可能是您设定了屏蔽彩色弹幕（按类型屏蔽选项），如果仍无法解决希望可以提供一下xml文件或者av号，文件请发送到hkm@tikm.org
另外基于qt的新版本就要做好了，增加了ass、json文件读取等许多新功能，敬请期待哦

**Comment by starxjys** [comment]
确认是播放器的问题，蟹蟹
